[project]
name = "midi-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.12.3",
    "httpx>=0.28.1",
    "mido>=1.3.3",
    "python-rtmidi>=1.5.8",
]
